# Generated by Django 2.1.2 on 2018-10-26 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hosted_link', models.CharField(max_length=50)),
                ('github_link', models.CharField(max_length=50)),
                ('screenshot', models.TextField()),
                ('description', models.TextField()),
                ('tech', models.TextField()),
                ('teammates', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('linkedin_link', models.CharField(max_length=50)),
                ('github_link', models.CharField(max_length=50)),
                ('website_link', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('skills', models.TextField()),
                ('favorite_snack', models.CharField(max_length=50)),
                ('dream_job', models.TextField()),
                ('favorite_tech', models.CharField(max_length=50)),
                ('hidden_talent', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
