# Generated by Django 2.1.2 on 2018-10-25 21:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dev_connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('screenshot', models.TextField()),
                ('description', models.TextField()),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('teammates', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dream_job',
            field=models.TextField(default='coder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='favorite_snack',
            field=models.CharField(default='chips', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='favorite_tech',
            field=models.CharField(default='javascript', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.TextField(default='replace image here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(default='San Francisco', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tag_line',
            field=models.CharField(default='skills to pay the billz', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
