# Generated by Django 2.1.2 on 2018-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_connect', '0002_auto_20181025_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teammates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(),
        ),
    ]
